services:
  redis:
    image: redis-cache:latest
    build: ./redis
    ports:
      - '6379:6379'
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - redis-data:/data
  WZDx_tim_translator:
    build: 
      context: .
      dockerfile: ./Translators/WZDx/Dockerfile
    image: translator:latest
    environment:
      - dual_carriageway_endpoint=${dual_carriageway_endpoint}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - WZDX_ENDPOINT=${WZDX_ENDPOINT}
      - WZDX_API_KEY=${WZDX_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - DURATION_TIME=${DURATION_TIME}
      - TIM_MANAGER_ENDPOINT=${TIM_MANAGER_ENDPOINT}
      - RUN_LOCAL=${RUN_LOCAL}
    ports: 
      - '8081:8081'
    logging:
      options:
        max-size: '10m'
        max-file: '5'
  Road_conditions_translator:
    build: ./Translators/RoadConditions
    image: rc_translator:latest
    environment:
      - dual_carriageway_endpoint=${dual_carriageway_endpoint}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - CDOT_FEED_ENDPOINT=${CDOT_FEED_ENDPOINT}
      - CDOT_FEED_API_KEY=${CDOT_FEED_API_KEY}
      - DURATION_TIME=${DURATION_TIME}
      - TIM_MANAGER_ENDPOINT=${TIM_MANAGER_ENDPOINT}
      - RUN_LOCAL=${RUN_LOCAL}
    ports: 
      - '8082:8082'
    logging:
      options:
        max-size: '10m'
        max-file: '5'
  Planned_Events_translator:
    build:
      context: .
      dockerfile: ./Translators/PlannedEvents/Dockerfile
    image: pe_translator:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - CDOT_FEED_ENDPOINT=${CDOT_FEED_ENDPOINT}
      - CDOT_FEED_API_KEY=${CDOT_FEED_API_KEY}
      - TIM_MANAGER_ENDPOINT=${TIM_MANAGER_ENDPOINT}
      - RUN_LOCAL=${RUN_LOCAL}
    ports: 
      - '8085:8085'
    logging:
      options:
        max-size: '10m'
        max-file: '5'
  VSL_tim_translator:
    build: 
      context: .
      dockerfile: ./Translators/Signs/Dockerfile
    image: vsl_translator:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - CDOT_FEED_ENDPOINT=${CDOT_FEED_ENDPOINT}
      - CDOT_FEED_API_KEY=${CDOT_FEED_API_KEY}
      - TIM_MANAGER_ENDPOINT=${TIM_MANAGER_ENDPOINT}
      - RUN_LOCAL=${RUN_LOCAL}
    ports: 
      - '8086:8086'
    logging:
      options:
        max-size: '10m'
        max-file: '5'

volumes:
  redis-data:
    driver: local