services:
  redis:
    image: redis-cache:latest
    build: ./redis
    ports:
      - '6379:6379'
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - redis-data:/data

  WZDx_tim_translator:
    build: ./Translators/WZDx
    image: translator:latest
    environment:
      - dual_carriageway_endpoint=${dual_carriageway_endpoint}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - CDOT_FEED_ENDPOINT=${CDOT_FEED_ENDPOINT}
      - CDOT_FEED_API_KEY=${CDOT_FEED_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - DURATION_TIME=${DURATION_TIME}
      - ODE_ENDPOINT=${ODE_ENDPOINT}
      - RUN_LOCAL=${RUN_LOCAL}
    ports: 
      - '8081:8081'
    logging:
      options:
        max-size: '10m'
        max-file: '5'

  Incident_translator:
    build: ./Translators/Incident
    image: incident_translator:latest
    environment:
      - dual_carriageway_endpoint=${dual_carriageway_endpoint}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - CDOT_FEED_ENDPOINT=${CDOT_FEED_ENDPOINT}
      - CDOT_FEED_API_KEY=${CDOT_FEED_API_KEY}
      - ODE_ENDPOINT=${ODE_ENDPOINT}
      - RUN_LOCAL=${RUN_LOCAL}
    ports: 
      - '8083:8083'
    logging:
      options:
        max-size: '10m'
        max-file: '5'

volumes:
  redis-data:
    driver: local