# Pipeline for creating and pushing Cloud Function artifacts

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - "Translators/WZDx/*"
    - "Translators/Shared/*"


pool:
  vmImage: ubuntu-latest

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'Translators/WZDx'
      Contents: 'Dockerfile'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'Translators/WZDx'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Translators/WZDx'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'Translators/Shared'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Translators/Shared'

  # Publish the artifacts directory for consumption in publish pipeline
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'tim-tools'
      publishLocation: 'Container'