# Pipeline for creating and pushing Cloud Function artifacts

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - "Translators/WZDx/*"


pool:
  vmImage: ubuntu-latest

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'services'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Publish the artifacts directory for consumption in publish pipeline
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'tim-tools'
      publishLocation: 'Container'